name: emacs
dependencies:
  - python=3.6
  - ipython
  - numpy
  - pandas
  - sqlalchemy
  - xarray
  - scikit-learn
  - yaml
  - psycopg2
  - flask
  - flake8
  - pip:
    - nameko
    - jedi
    - rope
    - importmagic
    - yapf
    - autopep8
    - mypy
    - flake8-docstrings
