name: emacs
dependencies:
  - python=3.6
  - pip
  - ipython
  - numpy
  - pandas
  - sqlalchemy
  - xarray
  - scikit-learn
  - yaml
  - psycopg2
  - flask
  - flake8
  - click
  - mypy
  - networkx
  - plotly
  - jinja2
  - requests
  - wrapt
  - pip:
    - nameko
    - nameko-sqlalchemy
    - apache-libcloud
    - jedi
    - rope
    - importmagic
    - yapf
    - autopep8
    - mypy
    - flake8-docstrings
    - apispec
    - marshmallow
    - marshmallow-sqlalchemy
    - cerberus
    - sqlalchemy-utils
    - cachetools
    - pendulum
